import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root=dirname(dirname(fileURLToPath(import.meta.url)));
test('help exposes Kodematik v0.6.13 locked baseline evaluation',()=>{
  const out=execFileSync(process.execPath,[join(root,'src','cli.js'),'help'],{encoding:'utf8'});
  assert.match(out,/Kodematik v0\.6\.13/);
  assert.match(out,/kodematik qualify/);
  assert.match(out,/kodematik baseline/);
  assert.match(out,/kodematik evolve/);
  assert.match(out,/--agent codex\|openrouter/);
  assert.match(out,/deepseek\/deepseek-v4-flash/);
  assert.match(out,/--tasks N/);
  assert.match(out,/--scan-limit N/);
  assert.match(out,/--expected-fingerprint SHA256/);
  assert.match(out,/--qualification-budget-min N/);
  assert.match(out,/--verification-timeout-sec N/);
  assert.match(out,/--install-timeout-sec N/);
  assert.match(out,/--holdout PERCENT/);
  assert.match(out,/--candidates N/);
  assert.match(out,/--max-turns N/);
  assert.match(out,/Locked Baseline Evaluation/);
  assert.match(out,/exact targeted historical test-oracle plan/);
  assert.match(out,/editing those oracle tests invalidates a pass/);
  assert.match(out,/optionally enforces an exact set fingerprint/);
  assert.match(out,/held-out KEEP gating/);
  assert.match(out,/--install/);
});
