import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root=dirname(dirname(fileURLToPath(import.meta.url)));
test('help exposes Kodematik v0.6.8 legacy compatibility and reproducibility guard',()=>{
  const out=execFileSync(process.execPath,[join(root,'src','cli.js'),'help'],{encoding:'utf8'});
  assert.match(out,/Kodematik v0\.6\.8/);
  assert.match(out,/kodematik qualify/);
  assert.match(out,/kodematik evolve/);
  assert.match(out,/--agent codex\|openrouter/);
  assert.match(out,/deepseek\/deepseek-v4-flash/);
  assert.match(out,/--tasks N/);
  assert.match(out,/--scan-limit N/);
  assert.match(out,/--holdout PERCENT/);
  assert.match(out,/--candidates N/);
  assert.match(out,/--max-turns N/);
  assert.match(out,/Legacy Toolchain Compatibility \+ Reproducibility Guard/);
  assert.match(out,/Node 4 → npm 2\.15\.11/);
  assert.match(out,/Node 6 → npm 3\.10\.10/);
  assert.match(out,/Node 8 → npm 5\.6\.0/);
  assert.match(out,/two-phase install/);
  assert.match(out,/fresh worktree/);
  assert.match(out,/qualified-set fingerprints/);
  assert.match(out,/token-free/);
  assert.match(out,/--install/);
});
