import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, mkdirSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { shell, detectRepo, evaluateTask, makeWorktree, removeWorktree, listReplayTasks, splitTasks, summarizeResults, decideEvolution, dependencyInstallCommand } from '../src/core.js';
import { selectMutations, rankTournament, tournamentWinner } from '../src/mutations.js';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'kodematik-fixture-'));shell('git',['init'],{cwd:dir});shell('git',['config','user.email','test@example.com'],{cwd:dir});shell('git',['config','user.name','Kodematik Test'],{cwd:dir});writeFileSync(join(dir,'package.json'),JSON.stringify({type:'module',scripts:{test:'node --test'}},null,2));writeFileSync(join(dir,'math.js'),'export const add = (a,b) => a-b;\n');mkdirSync(join(dir,'test'));writeFileSync(join(dir,'test/math.test.js'),"import test from 'node:test'; import assert from 'node:assert/strict'; import {add} from '../math.js'; test('add',()=>assert.equal(add(2,3),5));\n");shell('git',['add','.'],{cwd:dir});shell('git',['commit','-m','broken add'],{cwd:dir});writeFileSync(join(dir,'math.js'),'export const add = (a,b) => a+b;\n');shell('git',['add','.'],{cwd:dir});shell('git',['commit','-m','fix add'],{cwd:dir});writeFileSync(join(dir,'math.js'),'export const add = (a,b) => Number(a)+Number(b);\n');shell('git',['add','.'],{cwd:dir});shell('git',['commit','-m','coerce add inputs'],{cwd:dir});writeFileSync(join(dir,'README.md'),'# fixture\n');shell('git',['add','.'],{cwd:dir});shell('git',['commit','-m','docs only'],{cwd:dir});return dir;}
function patchAgent(cwd,_prompt,{task}){const patch=join(cwd,'.kodematik-ground-truth.patch');writeFileSync(patch,task.expectedPatch);const applied=shell('git',['apply','--whitespace=nowarn',patch],{cwd,allowFailure:true});rmSync(patch,{force:true});return{ok:applied.status===0,status:applied.status,events:[],usage:{input_tokens:10,output_tokens:5}};}
test('detectRepo identifies test script and git',()=>{const dir=fixture(),d=detectRepo(dir);assert.equal(d.root,dir);assert.equal(d.scripts.test,'node --test');});
test('dependency install command respects lockfiles',()=>{const dir=fixture();assert.deepEqual(dependencyInstallCommand(dir),['npm',['install']]);writeFileSync(join(dir,'package-lock.json'),'{}\n');assert.deepEqual(dependencyInstallCommand(dir),['npm',['ci']]);rmSync(join(dir,'package-lock.json'));writeFileSync(join(dir,'yarn.lock'),'# lock\n');assert.deepEqual(dependencyInstallCommand(dir),['yarn',['install','--frozen-lockfile']]);rmSync(join(dir,'yarn.lock'));writeFileSync(join(dir,'pnpm-lock.yaml'),'lockfileVersion: 9\n');assert.deepEqual(dependencyInstallCommand(dir),['pnpm',['install','--frozen-lockfile']]);});
test('worktree is isolated from source repository',()=>{const dir=fixture(),wt=makeWorktree(dir,'test');try{writeFileSync(join(wt,'math.js'),'changed\n');assert.match(readFileSync(join(dir,'math.js'),'utf8'),/Number/);}finally{removeWorktree(dir,wt);}assert.equal(existsSync(wt),false);});
test('replay task fails without agent when regression exists',()=>{const dir=fixture(),task=listReplayTasks(dir,{limit:4}).find(t=>t.title==='fix add');assert.ok(task);const result=evaluateTask(dir,task,{runAgent:false});assert.equal(result.pass,false);assert.equal(result.score,0);});
test('ground-truth patch agent solves replay task',()=>{const dir=fixture(),task=listReplayTasks(dir,{limit:4}).find(t=>t.title==='fix add'),result=evaluateTask(dir,task,{agentRunner:patchAgent});assert.equal(result.regressionDetected,true);assert.equal(result.pass,true);assert.equal(result.score,100);});
test('task with no failing pre-check cannot pass vacuously',()=>{const dir=fixture(),head=shell('git',['rev-parse','HEAD'],{cwd:dir}).stdout,task={id:'no-regression',title:'no regression',prompt:'do nothing',parent:head,touchedFiles:[]},result=evaluateTask(dir,task,{runAgent:false});assert.equal(result.regressionDetected,false);assert.equal(result.pass,false);assert.equal(result.score,100);});
test('non-regression task skips agent before spending tokens',()=>{const dir=fixture(),head=shell('git',['rev-parse','HEAD'],{cwd:dir}).stdout,task={id:'skip-agent',title:'skip agent',prompt:'do nothing',parent:head,touchedFiles:[]};let calls=0;const agent=()=>{calls++;return{ok:true,status:0,events:[],usage:{input_tokens:999,output_tokens:999}};};const result=evaluateTask(dir,task,{agentRunner:agent});assert.equal(result.usable,false);assert.equal(calls,0);assert.equal(result.agent.usage,null);assert.match(result.agent.stderr,/skipped/);});
test('listReplayTasks returns multiple commits',()=>{const dir=fixture(),tasks=listReplayTasks(dir,{limit:3});assert.equal(tasks.length,3);assert.equal(tasks[0].title,'docs only');assert.ok(tasks.every(t=>t.parent&&t.commit));});
test('splitTasks is deterministic',()=>{const tasks=Array.from({length:10},(_,i)=>({id:String(i)})),a=splitTasks(tasks,30),b=splitTasks(tasks,30);assert.equal(a.training.length,7);assert.equal(a.heldout.length,3);assert.deepEqual(a,b);assert.equal(new Set([...a.training,...a.heldout].map(t=>t.id)).size,10);});
test('suite summary ignores vacuous tasks and aggregates tokens',()=>{const s=summarizeResults([{usable:true,pass:true,score:100,agent:{usage:{input_tokens:10,output_tokens:2}}},{usable:true,pass:false,score:0,agent:{usage:{input_tokens:20,output_tokens:3}}},{usable:false,pass:false,score:100,agent:{usage:null}}]);assert.deepEqual(s,{total:3,usable:2,passed:1,score:50,passRate:50,inputTokens:30,outputTokens:5});});
test('evolution requires improvement and no held-out regression',()=>{const suite=(score,passRate,usable=2)=>({results:[],summary:{total:usable,usable,passed:Math.round(passRate*usable/100),score,passRate,inputTokens:0,outputTokens:0}});assert.equal(decideEvolution({trainingBaseline:suite(50,50),trainingCandidate:suite(100,100),heldoutBaseline:suite(50,50),heldoutCandidate:suite(50,50)}).keep,true);assert.equal(decideEvolution({trainingBaseline:suite(50,50),trainingCandidate:suite(100,100),heldoutBaseline:suite(100,100),heldoutCandidate:suite(50,50)}).keep,false);});
test('mutation catalog provides five distinct strategies',()=>{const mutations=selectMutations(5);assert.equal(mutations.length,5);assert.equal(new Set(mutations.map(m=>m.id)).size,5);});
test('mutation augments historical AGENTS instructions instead of deleting them',()=>{const dir=fixture(),task=listReplayTasks(dir,{limit:4}).find(t=>t.title==='fix add'),mutation={id:'preserve',apply(cwd){writeFileSync(join(cwd,'AGENTS.md'),'original guidance\nnew candidate\n');}};const result=evaluateTask(dir,task,{mutation,agentRunner:patchAgent});assert.equal(result.pass,true);assert.equal(existsSync(join(dir,'AGENTS.md')),false);});
test('tournament ranks pass rate, verification, then token cost',()=>{const entry=(id,passRate,score,tokens)=>({mutation:{id},suite:{summary:{passRate,score,inputTokens:tokens,outputTokens:0}}}),entries=[entry('a',50,100,5),entry('b',75,80,100),entry('c',75,90,200),entry('d',75,90,10)];const ranked=rankTournament(entries);assert.deepEqual(ranked.map(x=>x.mutation.id),['d','c','b','a']);assert.equal(tournamentWinner(entries).mutation.id,'d');});
