#!/usr/bin/env node
import { mkdirSync, cpSync } from 'node:fs';
import { join } from 'node:path';
import { detectRepo, listReplayTasks, evaluateSuite, splitTasks, decideEvolution } from './core.js';
import { selectMutations, rankTournament, tournamentWinner } from './mutations.js';

const args=process.argv.slice(2),cmd=args[0]||'help',cwd=process.cwd();
function flag(name){const i=args.indexOf(name);return i>=0?args[i+1]:null;} function has(name){return args.includes(name);} function intFlag(name,fallback){const n=Number.parseInt(flag(name)||'',10);return Number.isFinite(n)&&n>0?n:fallback;}
function emptySuite(){return{results:[],summary:{total:0,usable:0,passed:0,score:0,passRate:0,inputTokens:0,outputTokens:0}};}
function printReport(r){console.log('\nAGENTGYM — repository training baseline\n');for(const[name,ok]of r.checks)console.log(`${ok?'✓':'✗'} ${name}`);console.log(`\nReadiness metadata: ${r.score}/100`);console.log('Note: readiness is diagnostic metadata, not an agent-performance benchmark.');}
function doctor(){printReport(detectRepo(cwd));}
function init(){const target=join(cwd,'skills','agentgym');mkdirSync(target,{recursive:true});cpSync(new URL('../skills/agentgym/',import.meta.url),target,{recursive:true});console.log('Created skills/agentgym/ with SKILL.md and references.');}
function loadTasks(repo){const count=intFlag('--tasks',10),tasks=listReplayTasks(repo.root,{limit:count});if(!tasks.length)throw new Error('Need at least one non-merge commit with a parent and changed files.');return tasks;}
function printSuite(label,suite){const s=suite.summary;console.log(`\n${label}`);for(const r of suite.results){const marker=!r.usable?'SKIP':r.pass?'PASS':'FAIL';console.log(`${marker.padEnd(4)} ${r.taskId}  ${r.score.toString().padStart(3)}/100  ${r.title}`);}console.log(`Usable: ${s.usable}/${s.total} · Pass rate: ${s.passRate}% · Verification: ${s.score}/100`);if(s.inputTokens||s.outputTokens)console.log(`Tokens: in=${s.inputTokens} out=${s.outputTokens}`);}
function benchmark(){const repo=detectRepo(cwd);if(!repo.root)throw new Error('Run AgentGym inside a git repository.');const tasks=loadTasks(repo),suite=evaluateSuite(repo.root,tasks,{candidate:has('--candidate'),runAgent:!has('--no-agent'),model:flag('--model')});console.log(`\nBenchmarking ${tasks.length} replay task${tasks.length===1?'':'s'}...`);printSuite(has('--candidate')?'Candidate':'Baseline',suite);if(!suite.summary.usable)console.log('\nNo usable regression tasks were found: pre-fix verification must fail for a task to count.');}
function evolve(){const repo=detectRepo(cwd);printReport(repo);if(!repo.root)throw new Error('Run AgentGym inside a git repository.');const tasks=loadTasks(repo),{training,heldout}=splitTasks(tasks,intFlag('--holdout',30)),mutations=selectMutations(intFlag('--candidates',5)),options={runAgent:!has('--no-agent'),model:flag('--model')};console.log(`\nTask split: ${training.length} training · ${heldout.length} held-out`);console.log(`Evolution tournament: ${mutations.length} mutation candidates`);console.log('\nRunning training baseline...');const trainingBaseline=evaluateSuite(repo.root,training,{...options});const entries=[];for(const mutation of mutations){console.log(`Running candidate: ${mutation.title}...`);entries.push({mutation,suite:evaluateSuite(repo.root,training,{...options,mutation})});}printSuite('Training baseline',trainingBaseline);console.log('\nTraining tournament');console.log(`${'candidate'.padEnd(22)} pass rate  verify  tokens`);console.log(`${'baseline'.padEnd(22)} ${String(trainingBaseline.summary.passRate).padStart(3)}%       ${String(trainingBaseline.summary.score).padStart(3)}     ${trainingBaseline.summary.inputTokens+trainingBaseline.summary.outputTokens}`);const ranked=rankTournament(entries);for(let i=0;i<ranked.length;i++){const e=ranked[i],s=e.suite.summary;console.log(`${e.mutation.id.padEnd(22)} ${String(s.passRate).padStart(3)}%       ${String(s.score).padStart(3)}     ${s.inputTokens+s.outputTokens}${i===0?'  ← winner':''}`);}const winner=tournamentWinner(entries);if(!winner)throw new Error('No mutation candidates available.');console.log(`\nTraining winner: ${winner.mutation.title} (${winner.mutation.id})`);let heldoutBaseline=emptySuite(),heldoutWinner=emptySuite();if(heldout.length){console.log('\nValidating only the winner on held-out tasks...');heldoutBaseline=evaluateSuite(repo.root,heldout,{...options});heldoutWinner=evaluateSuite(repo.root,heldout,{...options,mutation:winner.mutation});printSuite('Held-out baseline',heldoutBaseline);printSuite(`Held-out winner · ${winner.mutation.title}`,heldoutWinner);}const decision=decideEvolution({trainingBaseline,trainingCandidate:winner.suite,heldoutBaseline,heldoutCandidate:heldoutWinner});console.log(`\nTraining delta: ${decision.training.scoreDelta>=0?'+':''}${decision.training.scoreDelta} score, ${decision.training.passRateDelta>=0?'+':''}${decision.training.passRateDelta} pass-rate points`);if(decision.hasHeldout)console.log(`Held-out delta: ${decision.heldout.scoreDelta>=0?'+':''}${decision.heldout.scoreDelta} score, ${decision.heldout.passRateDelta>=0?'+':''}${decision.heldout.passRateDelta} pass-rate points`);console.log(decision.keep?`KEEP ✓ ${winner.mutation.title} won training and did not regress held-out evaluation.`:'REJECT ✗ Tournament winner failed the train/held-out acceptance rule; repository is unchanged.');console.log('\nSafety: candidates run in detached temporary Git worktrees and only the training winner reaches held-out evaluation.');}
function help(){console.log(`AgentGym v0.4.0\n\nUsage:\n  agentgym doctor\n  agentgym benchmark [--tasks N] [--candidate] [--model MODEL] [--no-agent]\n  agentgym evolve [--tasks N] [--holdout PERCENT] [--candidates N] [--model MODEL] [--no-agent]\n  agentgym init\n\nv0.4 Actual Evolution:\n  evolve generates a mutation tournament, ranks candidates on training tasks,\n  then evaluates only the winner against the baseline on held-out tasks.\n\nDefaults: --tasks 10 · --holdout 30 · --candidates 5\nRequires Codex CLI for real agent runs. --no-agent exercises the harness without invoking Codex.\n`);}
try{if(cmd==='doctor')doctor();else if(cmd==='benchmark')benchmark();else if(cmd==='evolve')evolve();else if(cmd==='init')init();else help();}catch(e){console.error(`AgentGym error: ${e.message}`);process.exitCode=1;}
