import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';

export function shell(bin,args,{cwd=process.cwd(),allowFailure=false,timeout=120000,env=process.env,raw=false}={}){const cleanEnv={...env};delete cleanEnv.NODE_TEST_CONTEXT;const r=spawnSync(bin,args,{cwd,encoding:'utf8',timeout,env:cleanEnv});if(!allowFailure&&(r.error||r.status!==0)){const msg=r.error?.message||r.stderr||`${bin} exited ${r.status}`;throw new Error(msg.trim());}return{status:r.status??1,stdout:raw?(r.stdout||''):(r.stdout||'').trim(),stderr:raw?(r.stderr||''):(r.stderr||'').trim()};}
export function gitRoot(cwd=process.cwd()){const r=shell('git',['rev-parse','--show-toplevel'],{cwd,allowFailure:true});return r.status===0?r.stdout:null;}
export function readPackage(cwd){const p=join(cwd,'package.json');return existsSync(p)?JSON.parse(readFileSync(p,'utf8')):{};}
export function packageManager(cwd){if(existsSync(join(cwd,'pnpm-lock.yaml')))return'pnpm';if(existsSync(join(cwd,'yarn.lock')))return'yarn';return'npm';}
export function dependencyInstallCommand(cwd){if(existsSync(join(cwd,'pnpm-lock.yaml')))return['pnpm',['install','--frozen-lockfile']];if(existsSync(join(cwd,'yarn.lock')))return['yarn',['install','--frozen-lockfile']];if(existsSync(join(cwd,'package-lock.json')))return['npm',['ci']];return['npm',['install']];}
export function installRepositoryDependencies(cwd,{timeout=300000}={}){if(!existsSync(join(cwd,'package.json')))return{ok:true,skipped:true,command:null,status:0,stdout:'',stderr:''};const[bin,args]=dependencyInstallCommand(cwd),r=shell(bin,args,{cwd,allowFailure:true,timeout});return{ok:r.status===0,skipped:false,command:[bin,...args].join(' '),status:r.status,stdout:r.stdout,stderr:r.stderr};}
export function detectRepo(cwd=process.cwd()){const root=gitRoot(cwd),pkg=readPackage(cwd),scripts=pkg.scripts||{};const checks=[['git repository',!!root],['AGENTS.md',existsSync(join(cwd,'AGENTS.md'))],['agent skill',existsSync(join(cwd,'skills'))||existsSync(join(cwd,'.github','skills'))||existsSync(join(cwd,'.claude','skills'))],['test command',!!scripts.test],['typecheck command',!!scripts.typecheck||!!scripts['type-check']],['lint command',!!scripts.lint],['CI workflow',existsSync(join(cwd,'.github','workflows'))]];return{root,pkg,scripts,checks,score:Math.round(checks.filter(([,v])=>v).length/checks.length*100)};}
export function verificationCommands(cwd){const scripts=readPackage(cwd).scripts||{},pm=packageManager(cwd),run=name=>pm==='npm'?['npm',['run',name,'--if-present']]:[pm,[name]],out=[];if(scripts.test)out.push({name:'test',command:run('test')});if(scripts.typecheck)out.push({name:'typecheck',command:run('typecheck')});else if(scripts['type-check'])out.push({name:'type-check',command:run('type-check')});if(scripts.lint)out.push({name:'lint',command:run('lint')});return out;}
export function runVerification(cwd,commands=verificationCommands(cwd)){return commands.map(({name,command:[bin,args]})=>{const started=Date.now(),r=shell(bin,args,{cwd,allowFailure:true,timeout:180000});return{name,ok:r.status===0,status:r.status,ms:Date.now()-started,stdout:r.stdout,stderr:r.stderr};});}
export function scoreVerification(results){return results.length?Math.round(results.filter(x=>x.ok).length/results.length*100):0;}
export function makeWorktree(repo,label='run',ref='HEAD'){const base=join(tmpdir(),'kodematik');mkdirSync(base,{recursive:true});const dir=join(base,`${label}-${randomUUID().slice(0,8)}`);shell('git',['worktree','add','--detach',dir,ref],{cwd:repo});return dir;}
export function removeWorktree(repo,dir){shell('git',['worktree','remove','--force',dir],{cwd:repo,allowFailure:true});rmSync(dir,{recursive:true,force:true});}
export function runCodexTask(cwd,prompt,{model,timeout=300000}={}){const args=['exec','--json','--sandbox','workspace-write','--config','approval_policy="never"'];if(model)args.push('-m',model);args.push(prompt);const r=shell('codex',args,{cwd,allowFailure:true,timeout}),events=[];for(const line of r.stdout.split('\n').filter(Boolean)){try{events.push(JSON.parse(line));}catch{}}const completed=[...events].reverse().find(e=>e.type==='turn.completed');return{ok:r.status===0,status:r.status,events,usage:completed?.usage||null,stderr:r.stderr};}
export function gitDiff(cwd){return shell('git',['diff','--no-ext-diff','--binary'],{cwd,allowFailure:true,raw:true}).stdout;}
export function changedFiles(cwd){const out=shell('git',['status','--short'],{cwd,allowFailure:true}).stdout;return out?out.split('\n').map(x=>x.slice(3).trim()).filter(Boolean):[];}
export function createCandidateInstructions(cwd,repoInfo){const scripts=repoInfo.scripts||{},pm=packageManager(cwd),command=name=>pm==='npm'?`npm run ${name}`:`${pm} ${name}`,lines=['# AGENTS.md','','## Working agreement','- Make the smallest change that solves the task.','- Do not modify existing tests merely to make failures disappear.','- Avoid editing generated/vendor/build output unless the task explicitly requires it.','- Before finishing, run the repository verification commands that are available.',''];if(scripts.test)lines.push(`- Test: \`${pm==='npm'?'npm test':`${pm} test`}\``);if(scripts.typecheck)lines.push(`- Typecheck: \`${command('typecheck')}\``);if(scripts['type-check'])lines.push(`- Typecheck: \`${command('type-check')}\``);if(scripts.lint)lines.push(`- Lint: \`${command('lint')}\``);lines.push('','## Verification','Report which checks you ran and whether they passed.','');writeFileSync(join(cwd,'AGENTS.md'),lines.join('\n'));}
export function makeTaskFromCommit(repo,commit){const meta=shell('git',['show','-s','--format=%H%x09%P%x09%s',commit],{cwd:repo,allowFailure:true});if(meta.status!==0||!meta.stdout)return null;const[hash,parents,...subjectParts]=meta.stdout.split('\t'),parentList=(parents||'').split(' ').filter(Boolean);if(parentList.length!==1)return null;const parent=parentList[0],files=shell('git',['diff','--name-only',parent,hash],{cwd:repo}).stdout.split('\n').filter(Boolean);if(!files.length)return null;return{id:hash.slice(0,12),commit:hash,title:subjectParts.join('\t')||`Replay ${hash.slice(0,8)}`,prompt:'A regression exists in this repository. Diagnose and fix it. Preserve existing tests and make the smallest correct change. Before finishing, run the relevant verification commands.',parent,expectedPatch:shell('git',['diff','--binary',parent,hash],{cwd:repo,raw:true}).stdout,touchedFiles:files};}
export function makeTaskFromLastCommit(repo){return makeTaskFromCommit(repo,'HEAD');}
export function listReplayTasks(repo,{limit=10,scanLimit=Math.max(limit*5,25)}={}){const r=shell('git',['log',`--max-count=${scanLimit}`,'--format=%H'],{cwd:repo,allowFailure:true});if(r.status!==0)return[];const tasks=[];for(const hash of r.stdout.split('\n').filter(Boolean)){const task=makeTaskFromCommit(repo,hash);if(task)tasks.push(task);if(tasks.length>=limit)break;}return tasks;}
export function splitTasks(tasks,holdoutPercent=30){if(tasks.length<=1)return{training:tasks,heldout:[]};const pct=Math.min(50,Math.max(10,Number(holdoutPercent)||30)),heldoutCount=Math.max(1,Math.min(tasks.length-1,Math.round(tasks.length*pct/100))),heldoutIndexes=new Set();for(let i=0;i<heldoutCount;i++)heldoutIndexes.add(Math.min(tasks.length-1,Math.floor((i+0.5)*tasks.length/heldoutCount)));const training=[],heldout=[];tasks.forEach((task,i)=>(heldoutIndexes.has(i)?heldout:training).push(task));return{training,heldout};}
export function resetWorktreeTo(worktree,commit){shell('git',['reset','--hard',commit],{cwd:worktree});shell('git',['clean','-fd'],{cwd:worktree});}
export function qualifyTask(repo,task,{installDependencies=false}={}){const wt=makeWorktree(repo,'qualify',task.parent);try{resetWorktreeTo(wt,task.parent);const preparation=installDependencies?installRepositoryDependencies(wt):{ok:true,skipped:true,command:null,status:0,stdout:'',stderr:''};const before=preparation.ok?runVerification(wt):[],regressionDetected=before.some(x=>!x.ok),usable=preparation.ok&&regressionDetected&&before.length>0;return{taskId:task.id,preparation,before,regressionDetected,usable};}finally{removeWorktree(repo,wt);}}
export function prequalifyTasks(repo,tasks,{installDependencies=false}={}){return tasks.map(task=>({task,qualification:qualifyTask(repo,task,{installDependencies})}));}
export function evaluateTask(repo,task,{candidate=false,mutation=null,runAgent=true,model,installDependencies=false,agentRunner=runCodexTask,maxTurns}={}){const label=mutation?.id|| (candidate?'candidate':'baseline'),wt=makeWorktree(repo,label,task.parent);try{resetWorktreeTo(wt,task.parent);const preparation=installDependencies?installRepositoryDependencies(wt):{ok:true,skipped:true,command:null,status:0,stdout:'',stderr:''},info=detectRepo(wt);if(mutation)mutation.apply(wt,info);else if(candidate)createCandidateInstructions(wt,info);const before=preparation.ok?runVerification(wt):[],regressionDetected=before.some(x=>!x.ok);if(!preparation.ok||!regressionDetected||before.length===0){return{taskId:task.id,title:task.title,variant:mutation?.id||(candidate?'candidate':'baseline'),score:scoreVerification(before),preparation,before,after:before,agent:{ok:false,status:0,usage:null,events:[],stderr:'skipped: task is not a usable regression'},files:[],testFilesTouched:[],diff:'',regressionDetected,usable:false,pass:false};}const agent=runAgent?agentRunner(wt,task.prompt,{model,task,mutation,maxTurns}):{ok:true,status:0,usage:null,events:[],stderr:''},after=runVerification(wt),files=changedFiles(wt),score=scoreVerification(after),testFilesTouched=files.filter(f=>/(^|\/)(__tests__|tests?|specs?)(\/|\.)|\.(test|spec)\./i.test(f)),usable=true;return{taskId:task.id,title:task.title,variant:mutation?.id||(candidate?'candidate':'baseline'),score,preparation,before,after,agent,files,testFilesTouched,diff:gitDiff(wt),regressionDetected,usable,pass:usable&&after.every(x=>x.ok)&&testFilesTouched.length===0};}finally{removeWorktree(repo,wt);}}
export function summarizeResults(results){const usable=results.filter(r=>r.usable),passed=usable.filter(r=>r.pass).length,score=usable.length?Math.round(usable.reduce((s,r)=>s+r.score,0)/usable.length):0,passRate=usable.length?Math.round(passed/usable.length*100):0,inputTokens=results.reduce((n,r)=>n+(r.agent?.usage?.input_tokens||0),0),outputTokens=results.reduce((n,r)=>n+(r.agent?.usage?.output_tokens||0),0);return{total:results.length,usable:usable.length,passed,score,passRate,inputTokens,outputTokens};}
export function evaluateSuite(repo,tasks,options={}){const results=tasks.map(task=>evaluateTask(repo,task,options));return{results,summary:summarizeResults(results)};}
export function compareSuites(baseline,candidate){const b=baseline.summary,c=candidate.summary;return{scoreDelta:c.score-b.score,passRateDelta:c.passRate-b.passRate,candidateBetter:c.score>b.score||c.passRate>b.passRate,candidateNotWorse:c.score>=b.score&&c.passRate>=b.passRate};}
export function decideEvolution({trainingBaseline,trainingCandidate,heldoutBaseline,heldoutCandidate}){const training=compareSuites(trainingBaseline,trainingCandidate),heldout=compareSuites(heldoutBaseline,heldoutCandidate),hasHeldout=heldoutBaseline.summary.usable>0||heldoutCandidate.summary.usable>0,keep=training.candidateBetter&&training.candidateNotWorse&&(!hasHeldout||heldout.candidateNotWorse);return{keep,training,heldout,hasHeldout};}
