import { existsSync, readFileSync, readdirSync, realpathSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

function major(value){const m=String(value||'').match(/(?:^|[^0-9])(\d{1,2})(?:\.|\b)/);return m?Number(m[1]):null;}
function unique(values){return [...new Set(values.filter(Number.isFinite))];}
function workflowNodeMajors(cwd){const dir=join(cwd,'.github','workflows');if(!existsSync(dir))return[];const values=[];for(const name of readdirSync(dir)){if(!/\.ya?ml$/i.test(name))continue;const text=readFileSync(join(dir,name),'utf8');for(const match of text.matchAll(/node-version\s*:\s*['"]?([^\n#'"]+)/gi)){const n=major(match[1]);if(n)values.push(n);}for(const match of text.matchAll(/^\s*-\s*['"]?(\d{1,2})(?:\.x)?['"]?\s*$/gm)){const n=Number(match[1]);if(n>=10&&n<=40)values.push(n);}}return unique(values).sort((a,b)=>b-a);}
function fileNodeMajor(cwd){for(const file of ['.nvmrc','.node-version']){const path=join(cwd,file);if(existsSync(path)){const n=major(readFileSync(path,'utf8').trim());if(n)return{major:n,source:file};}}return null;}
function packageNodeMajor(cwd){const path=join(cwd,'package.json');if(!existsSync(path))return null;try{const pkg=JSON.parse(readFileSync(path,'utf8'));const n=major(pkg.engines?.node);return n?{major:n,source:'package.json#engines.node',range:pkg.engines.node}:null;}catch{return null;}}
function which(bin){const r=spawnSync('which',[bin],{encoding:'utf8'});if(r.status!==0)return null;const p=(r.stdout||'').trim();if(!p)return null;try{return realpathSync(p);}catch{return p;}}
export function detectHistoricalRuntime(cwd){const explicit=fileNodeMajor(cwd),workflow=workflowNodeMajors(cwd),pkg=packageNodeMajor(cwd),current=Number(process.versions.node.split('.')[0]);let selected=null,source=null;if(explicit){selected=explicit.major;source=explicit.source;}else if(workflow.length){selected=workflow[0];source='historical-ci';}else if(pkg){selected=pkg.major;source=pkg.source;}return{currentNodeMajor:current,selectedNodeMajor:selected||current,source:source||'current-runtime',workflowNodeMajors:workflow,engineRange:pkg?.range||null,usesHistoricalNode:Boolean(selected&&selected!==current)};}
export function commandForRuntime(bin,args,runtime){if(!runtime?.usesHistoricalNode)return[bin,args];const nodeMajor=runtime.selectedNodeMajor;if(bin==='node')return['npx',['--yes',`node@${nodeMajor}`,...args]];if(bin==='npm'){const npmCli=which('npm');if(npmCli)return['npx',['--yes',`node@${nodeMajor}`,npmCli,...args]];}return[bin,args];}
export function runtimeSummary(runtime){const tested=runtime.workflowNodeMajors.length?` · historical CI [${runtime.workflowNodeMajors.join(', ')}]`:'';const engines=runtime.engineRange?` · engines ${runtime.engineRange}`:'';return`Node ${runtime.selectedNodeMajor} (${runtime.source})${tested}${engines}`;}
